# Generated by Django 3.1.6 on 2021-03-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_orderlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billnumber',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
