# Generated by Django 3.1.6 on 2021-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210314_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlines',
            name='amount',
            field=models.CharField(max_length=120),
        ),
    ]
