# Generated by Django 3.1.6 on 2021-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20210315_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='selling_price',
            field=models.FloatField(),
        ),
    ]
